-- Migration: Importer stock change history
-- Timestamp: 20260804180000
--
-- Tracks every real change to products.importer_stock (old -> new, when, and
-- whether it came from the scraper's bulk sync). The scraper/sync script
-- writes to every product's importer_stock on every run regardless of
-- whether the number actually moved, so this only logs when the value
-- genuinely changes (OLD IS DISTINCT FROM NEW) -- otherwise this table would
-- grow by ~one row per SKU on every single run of
-- actualizar_stock_importadora.py, most of which carry no real information.

CREATE TABLE IF NOT EXISTS public.importer_stock_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id),
    sku TEXT,
    old_stock NUMERIC,
    new_stock NUMERIC,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_importer_stock_history_product_id ON public.importer_stock_history(product_id);
CREATE INDEX IF NOT EXISTS idx_importer_stock_history_changed_at ON public.importer_stock_history(changed_at);

ALTER TABLE public.importer_stock_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access for authenticated users" ON public.importer_stock_history
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert access for authenticated users" ON public.importer_stock_history
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE OR REPLACE FUNCTION trg_log_importer_stock_change()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.importer_stock_history (product_id, sku, old_stock, new_stock)
    VALUES (NEW.id, NEW.sku, OLD.importer_stock, NEW.importer_stock);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_products_log_importer_stock_change ON public.products;
CREATE TRIGGER trg_products_log_importer_stock_change
AFTER UPDATE OF importer_stock ON public.products
FOR EACH ROW
WHEN (OLD.importer_stock IS DISTINCT FROM NEW.importer_stock)
EXECUTE FUNCTION trg_log_importer_stock_change();
