-- Migration: Add Brands Table and Relation
-- Description: Adds brands table and links it to products.

-- 1. Create Brands Table
CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true
);

-- Enable RLS
ALTER TABLE brands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access for authenticated users" ON brands FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow insert access for authenticated users" ON brands FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update access for authenticated users" ON brands FOR UPDATE TO authenticated USING (true);

-- 2. Add brand_id to Products
ALTER TABLE products
ADD COLUMN IF NOT EXISTS brand_id BIGINT REFERENCES brands(id);

-- Optional: Index for faster searches
CREATE INDEX IF NOT EXISTS idx_products_brand_id ON products(brand_id);
