-- Migration: Product price change history + raw importer price observations
-- Timestamp: 20260804190000
--
-- Two separate logs, because they answer two different questions:
--
-- 1. product_price_history: "what actually changed on MY products" -- any
--    real change to products.price or products.cost_without_vat, from any
--    source (manual edit, batch invoice entry, reactivation on re-import,
--    etc). Same change-only pattern as importer_stock_history: only logs
--    when the value truly differs, not on every write.
--
-- 2. importer_price_observations: "what the importer's site showed" --
--    independent of whether that value was ever applied to the product.
--    scripts/sync-odoo-products.js currently computes a fresh price for
--    every active product on every run but deliberately discards it in
--    memory without writing it anywhere (see the commented-out
--    productsToUpdate push, left disabled on purpose to avoid accidental
--    price drops on active inventory). That means today there is zero trace
--    of what the importer actually showed for active products -- this table
--    is what scripts/sync-odoo-products.js writes to instead, whenever the
--    observed cost differs from what's stored, so nothing is lost even when
--    we choose not to apply it.

CREATE TABLE IF NOT EXISTS public.product_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id),
    sku TEXT,
    old_price NUMERIC,
    new_price NUMERIC,
    old_cost_without_vat NUMERIC,
    new_cost_without_vat NUMERIC,
    changed_by UUID REFERENCES auth.users(id),
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_product_price_history_product_id ON public.product_price_history(product_id);
CREATE INDEX IF NOT EXISTS idx_product_price_history_changed_at ON public.product_price_history(changed_at);

ALTER TABLE public.product_price_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access for authenticated users" ON public.product_price_history
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert access for authenticated users" ON public.product_price_history
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE OR REPLACE FUNCTION trg_log_product_price_change()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.product_price_history (
        product_id, sku, old_price, new_price, old_cost_without_vat, new_cost_without_vat, changed_by
    ) VALUES (
        NEW.id, NEW.sku, OLD.price, NEW.price, OLD.cost_without_vat, NEW.cost_without_vat, auth.uid()
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_products_log_price_change ON public.products;
CREATE TRIGGER trg_products_log_price_change
AFTER UPDATE OF price, cost_without_vat ON public.products
FOR EACH ROW
WHEN (OLD.price IS DISTINCT FROM NEW.price OR OLD.cost_without_vat IS DISTINCT FROM NEW.cost_without_vat)
EXECUTE FUNCTION trg_log_product_price_change();

-- Raw importer observations: written directly by sync-odoo-products.js
-- (service role), not by a trigger, since the value it captures never
-- necessarily touches the products row.
CREATE TABLE IF NOT EXISTS public.importer_price_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id),
    sku TEXT NOT NULL,
    observed_cost_without_vat NUMERIC,
    observed_pvp NUMERIC,
    db_cost_without_vat NUMERIC,
    db_price NUMERIC,
    applied_to_product BOOLEAN DEFAULT false,
    observed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_importer_price_observations_product_id ON public.importer_price_observations(product_id);
CREATE INDEX IF NOT EXISTS idx_importer_price_observations_observed_at ON public.importer_price_observations(observed_at);

ALTER TABLE public.importer_price_observations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access for authenticated users" ON public.importer_price_observations
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow insert access for authenticated users" ON public.importer_price_observations
    FOR INSERT TO authenticated WITH CHECK (true);
